general:
  label: BASE
  random_seed: 1
training:
  anchor_epoch: 350
  target_radius: 0.1
  total_epochs: 700
checkpoint:
  save_epochs:
  save_frequency: 50
dataset:
  anchor: dataset/anchors_may07.csv
  anchor_freq: 10
  anchor_sets:
    - 1
  plaut: dataset/plaut_may07.csv
  probe: dataset/probes_may07.csv
outputs:
  activations:
    hidden:
      anchor: 10
      plaut: 50
      probe: 10
    output:
      anchor: 10
      plaut: 50
      probe: 10
  plotting:
    anchor_acc: 50
    loss: 50
    plaut_acc: 50
    probe_acc: 50
    running_time: 700
  sim_results: 1
  weights: 10

optimizers:
  1:
    learning_rate: 0.0001
    momentum: 0
    optimizer: SGD
    weight_decay: 1.0e-6
  11:
    learning_rate: 0.01
    momentum: 0
    optimizer: Adam
    weight_decay: 1.0e-6
  351:
    learning_rate: 0.01
    momentum: 0
    optimizer: Adam
    weight_decay: 1.0e-6
